import "./globals.css";
import { Lexend_Deca } from "next/font/google";
import Header from "@/component/Header";
import style from "./page.module.css";
import Footer from "@/component/Footer";
import { Providers } from "@/store/provider";

const lexendDeca = Lexend_Deca({
  subsets: ["vietnamese"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className={`${lexendDeca.className} ${style.body}`} suppressHydrationWarning={true}>
          <Header />
          <Providers>{children}</Providers>
          <Footer />
      </body>
    </html>
  );
}
