import "./globals.css";
import { Roboto } from "next/font/google";
import Header from "@/component/header";
import style from "./page.module.css";
import Footer from "@/component/footer";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${style.body}`}>
          <Header />
          {children}
          <Footer/>
      </body>
    </html>
  );
}
