import "./globals.css";
import { Lexend_Deca } from "next/font/google";
import Header from "@/component/header";
import style from "./page.module.css";
import Footer from "@/component/footer";


const lexendDeca = Lexend_Deca({
  subsets: ["vietnamese"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lexendDeca.className} ${style.body}`}>
          <Header />
          {children}
          <Footer />
      </body>
    </html>
  );
}
